let xp=0;
const state={talked:{marina:false,rafael:false,camila:false},events:[],journal:[]};
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');syncXP()}
function syncXP(){$('xp').textContent=xp;document.querySelectorAll('.xpMirror').forEach(x=>x.textContent=xp)}
function logEvent(q,a,c,tag){state.events.push({question:q,answer:a,correct:c,tag,time:new Date().toISOString()});console.table(state.events)}
function addJournal(title,text){if(!state.journal.some(x=>x.title===title))state.journal.push({title,text})}
function openJournal(){renderJournal();$('journal').classList.remove('hidden')} function closeJournal(){$('journal').classList.add('hidden')}
function renderJournal(){$('journalEntries').innerHTML=state.journal.length?state.journal.map(e=>`<div class="entry"><b>${e.title}</b><p>${e.text}</p></div>`).join(''):'<p>Você ainda não registrou nenhuma observação.</p>'}
function startGame(){show('map')} function goFaculty(){alert('Sua primeira atividade acontece na Escola Municipal. Procure o símbolo ! no mapa.')}
function goSchool(){show('scene');introDirector()} function dialog(x){$('dialog').innerHTML=x}
function speaker(icon,name){return `<div class="speaker"><span class="portrait">${icon}</span><b>${name}</b></div>`}
function introDirector(){ $('npcs').innerHTML=`<button class="npc">${'<span class="bang">!</span>'}👩‍💼<label>Marina • Diretora</label></button>`;
dialog(`${speaker('👩‍💼','MARINA — DIRETORA')}<p>Sejam bem-vindos! É muito bom ter estudantes de Medicina conosco.</p><p>Antes de começarmos, gostaria de saber: <strong>o que vocês pretendem fazer na escola?</strong></p><div class="answers">
${ans('A','Viemos ensinar à comunidade quais são os principais cuidados com a saúde das crianças.')}
${ans('B','Viemos identificar uma doença importante na escola e desenvolver um projeto para solucioná-la.')}
${ans('C','Primeiro queremos conhecer a escola e ouvir quais necessidades de saúde são percebidas pela comunidade.')}
${ans('D','Viemos coletar informações para realizar uma pesquisa sobre a saúde dos alunos.')}</div>`)}
function ans(l,t){return `<button class="answer" onclick="firstAnswer('${l}')"><b>${l}.</b> ${t}</button>`}
const fb1={A:['Antes de propor uma ação, é importante conhecer o contexto e ouvir os envolvidos. A universidade não deve presumir que já conhece as necessidades da comunidade.','PREDEFINE_NECESSIDADE'],B:['Definir previamente o problema pode fazer com que o projeto responda mais aos interesses da universidade do que às necessidades percebidas pela comunidade.','DEFINE_SEM_ESCUTA'],D:['Uma pesquisa pode produzir conhecimento, mas nossa missão neste momento é conhecer a comunidade e identificar, junto a ela, necessidades que possam orientar uma ação de extensão.','CONFUNDE_PESQUISA_EXTENSAO']};
function firstAnswer(l){if(l==='C'){logEvent('EXT_001',l,true,'ESCUTA');xp+=10;addJournal('👂 Escuta da comunidade','Antes de propor soluções, é necessário compreender o contexto e reconhecer as necessidades percebidas pelas pessoas envolvidas.');dialog(`${speaker('👩‍💼','MARINA — DIRETORA')}<p>“Ótimo! Quem vive a rotina da escola pode ajudar vocês a compreender melhor o que está acontecendo por aqui.”</p><div class="feedback good"><b>✨ NOVA HABILIDADE — ESCUTA DA COMUNIDADE</b><p>A construção de uma ação extensionista começa pelo diálogo com a comunidade.</p><p>⭐ +10 XP</p></div><button class="continue" onclick="openConversations()">CONTINUAR →</button>`)}else{let f=fb1[l];logEvent('EXT_001',l,false,f[1]);dialog(`${speaker('📖','CADERNO DE CAMPO')}<div class="feedback"><b>REVEJA SUA DECISÃO</b><p>${f[0]}</p></div><button class="continue" onclick="introDirector()">TENTAR NOVAMENTE</button>`)}}
const people={marina:{icon:'👩‍💼',name:'Marina • Diretora',text:'Nos últimos meses, recebemos comunicados da UBS informando que há crianças da escola com vacinas atrasadas. Também percebemos que algumas famílias têm dúvidas sobre quando devem procurar a unidade de saúde.',note:'A escola recebeu informações da UBS sobre crianças com vacinação atrasada.'},rafael:{icon:'👨‍🏫',name:'Rafael • Professor',text:'Já ouvi responsáveis dizerem que achavam que, depois das vacinas dos primeiros anos de vida, não precisariam mais se preocupar. Outros dizem que não sabem se a vacinação da criança está realmente em dia.',note:'Existem dúvidas das famílias sobre o calendário e a situação vacinal das crianças.'},camila:{icon:'👩‍🏫',name:'Camila • Professora',text:'Quando conversamos com as famílias, aparecem situações diferentes. Algumas dizem que não tiveram tempo de levar a criança à unidade. Outras têm dúvidas sobre as vacinas, e há famílias que dizem preferir não vacinar.',note:'Diferentes fatores podem estar relacionados ao atraso vacinal.'}};
function openConversations(){renderNPCs();dialog(`${speaker('📋','MISSÃO — OUVIR A COMUNIDADE ESCOLAR')}<p>Marina apresenta profissionais que acompanham as crianças diariamente.</p><p><b>Converse com todos os personagens marcados com !</b></p>`)}
function renderNPCs(){$('npcs').innerHTML=Object.entries(people).map(([k,p])=>`<button class="npc ${state.talked[k]?'done':''}" onclick="talk('${k}')">${state.talked[k]?'':'<span class="bang">!</span>'}${p.icon}<label>${p.name}</label></button>`).join('')}
function talk(k){let p=people[k];state.talked[k]=true;logEvent('NPC_'+k,'view',true,'DIALOG_VIEW');addJournal('📌 '+p.name,p.note);renderNPCs();let all=Object.values(state.talked).every(Boolean);dialog(`${speaker(p.icon,p.name.toUpperCase())}<p>“${p.text}”</p><div class="feedback good"><b>📌 REGISTRO NO CADERNO</b><p>${p.note}</p></div>${all?'<button class="continue" onclick="criticalQuestion()">REUNIR AS INFORMAÇÕES →</button>':'<p><small>Continue ouvindo os demais profissionais.</small></p>'}`)}
function criticalQuestion(){dialog(`${speaker('📖','CADERNO DE CAMPO')}<p>Depois de conversar com os profissionais, qual conclusão é mais adequada <b>neste momento</b>?</p><div class="answers">
${crit('A','As famílias não vacinam as crianças porque não conhecem a importância das vacinas.')}
${crit('B','A escola apresenta baixa cobertura vacinal causada principalmente pela falta de informação dos responsáveis.')}
${crit('C','A comunidade escolar identifica crianças com vacinação atrasada e relata diferentes situações que podem estar relacionadas ao problema.')}
${crit('D','As famílias que não vacinam seus filhos precisam receber atividades educativas sobre a importância das vacinas.')}</div>`)}
function crit(l,t){return `<button class="answer" onclick="criticalAnswer('${l}')"><b>${l}.</b> ${t}</button>`}
const fb2={A:['A falta de conhecimento foi mencionada em algumas situações, mas também foram relatadas outras possíveis razões. Ainda não podemos afirmar uma única causa.','GENERALIZACAO_CAUSAL'],B:['As conversas indicam vacinação atrasada, mas não permitem medir a cobertura vacinal nem estabelecer sua principal causa.','EXTRAPOLA_EVIDENCIA'],D:['Uma atividade educativa pode fazer parte de um projeto, mas ainda não sabemos se essa é a única ou a melhor resposta à necessidade identificada.','INTERVENCAO_PREMATURA']};
function criticalAnswer(l){if(l==='C'){logEvent('ESCUTA_002',l,true,'INTERPRETACAO_ADEQUADA');xp+=10;addJournal('🧠 Escuta crítica','Diferenciar aquilo que foi efetivamente relatado das explicações que ainda precisam ser investigadas.');dialog(`${speaker('✨','HABILIDADE DESBLOQUEADA')}<div class="feedback good"><b>ESCUTA CRÍTICA</b><p>Você diferenciou aquilo que foi efetivamente relatado pela comunidade das explicações que ainda precisariam ser investigadas.</p><p>Sabemos que existe uma <b>necessidade percebida relacionada à vacinação infantil</b>, mas ainda não podemos afirmar quais são suas causas.</p><p>⭐ +10 XP</p></div><p><b>Marina:</b> “A UBS acompanha a vacinação das crianças da região. Talvez seja importante conversar com a equipe de saúde.”</p><button class="continue" onclick="unlockUBS()">VOLTAR AO MAPA →</button>`)}else{let f=fb2[l];logEvent('ESCUTA_002',l,false,f[1]);dialog(`${speaker('📖','CADERNO DE CAMPO')}<div class="feedback"><b>ANALISE COM CUIDADO</b><p>${f[0]}</p></div><button class="continue" onclick="criticalQuestion()">REVER DECISÃO</button>`)}}
function unlockUBS(){$('ubsBtn').disabled=false;$('ubsBtn').classList.remove('locked');$('ubsLock').textContent='!';$('schoolMark').textContent='✓';$('mapHint').textContent='Novo local disponível: UBS Vila Aurora.';$('missionTop').textContent='Investigue a situação da vacinação infantil';show('map')}
function finishPrototype(){$('finalXp').textContent=xp;show('end')} function restart(){location.reload()}
